# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.3
language: objective-c
xcode_project: TinyPartTests.xcodeproj # path to your xcodeproj folder
xcode_scheme: TinyPartTests
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
