# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.3

language: objective-c
script: xcodebuild -project TinyPart.xcodeproj -scheme TinyPartTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO